version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: nginx_mruby_db_container
    image: nginx_mruby/db
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"

  nginx_mruby_sample:
    build:
      context: ./mruby_docker
      dockerfile: Dockerfile
    image: ngx_mruby/mysample
    container_name: nginx_mruby_container
    volumes:
      - ./nginx/conf:/usr/local/nginx/conf
      - ./nginx/hook:/usr/local/nginx/hook
    ports:
      - 80:80
    links:
      - db
    depends_on:
      - db
