version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: nginx_mruby/db
    ports:
      - 33306:3306
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"

  nginx_mruby_sample:
    build:
      context: ./mruby_docker
      dockerfile: Dockerfile
    image: matsumotory/ngx-mruby
    volumes:
      - ./docker/conf:/usr/local/nginx/conf
      - ./docker/hook:/usr/local/nginx/hook
    ports:
      - 80:80
    links:
      - db
volumes:
  db:
